"""schema inicial

Revision ID: 0001
Revises:
Create Date: 2026-07-15 18:17:56.610181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ig_user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_ref', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_ig_user_id'), 'accounts', ['ig_user_id'], unique=True)
    op.create_table('angulos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_angulos_account_name')
    )
    op.create_table('categorias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_categorias_account_name')
    )
    op.create_table('formatos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_formatos_account_name')
    )
    op.create_table('ingest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reels_processed', sa.Integer(), nullable=False),
    sa.Column('snapshots_written', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_temas_account_name')
    )
    op.create_table('tipos_hook',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_tipos_hook_account_name')
    )
    op.create_table('reels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('ig_media_id', sa.String(length=64), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('media_product_type', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('guion', sa.Text(), nullable=True),
    sa.Column('angulo_id', sa.String(length=36), nullable=True),
    sa.Column('formato_id', sa.String(length=36), nullable=True),
    sa.Column('tipo_hook_id', sa.String(length=36), nullable=True),
    sa.Column('categoria_id', sa.String(length=36), nullable=True),
    sa.Column('tema_id', sa.String(length=36), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['angulo_id'], ['angulos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['formato_id'], ['formatos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tema_id'], ['temas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_hook_id'], ['tipos_hook.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reels_ig_media_id'), 'reels', ['ig_media_id'], unique=True)
    op.create_table('reel_metric_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reel_id', sa.String(length=36), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('saved', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('avg_watch_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('total_watch_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reel_id', 'snapshot_date', name='uq_snapshot_reel_date')
    )
    op.create_index(op.f('ix_reel_metric_snapshots_snapshot_date'), 'reel_metric_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###

    # Vista de últimas métricas por reel + ratios (una fila por reel: el snapshot más reciente).
    op.execute("""
        CREATE VIEW reel_latest_metrics AS
        SELECT DISTINCT ON (s.reel_id)
            s.reel_id,
            s.captured_at,
            s.snapshot_date,
            s.reach, s.views, s.likes, s.comments, s.saved, s.shares,
            s.total_interactions,
            s.avg_watch_time_ms,
            s.total_watch_time_ms,
            (s.avg_watch_time_ms / 1000.0) AS avg_watch_time_sec,
            (s.total_interactions::float / NULLIF(s.reach, 0)) AS engagement_rate,
            (s.saved::float / NULLIF(s.reach, 0)) AS save_rate,
            (s.shares::float / NULLIF(s.reach, 0)) AS share_rate
        FROM reel_metric_snapshots s
        ORDER BY s.reel_id, s.snapshot_date DESC, s.captured_at DESC;
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS reel_latest_metrics;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reel_metric_snapshots_snapshot_date'), table_name='reel_metric_snapshots')
    op.drop_table('reel_metric_snapshots')
    op.drop_index(op.f('ix_reels_ig_media_id'), table_name='reels')
    op.drop_table('reels')
    op.drop_table('tipos_hook')
    op.drop_table('temas')
    op.drop_table('ingest_runs')
    op.drop_table('formatos')
    op.drop_table('categorias')
    op.drop_table('angulos')
    op.drop_index(op.f('ix_accounts_ig_user_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
